spring.application.name=Carepoint

# Server Configuration
server.port=8081

# MongoDB Configuration
# For local MongoDB instance:
spring.data.mongodb.uri=mongodb://localhost:27017/hospital_db

# JWT Secret Key (Keep this secret and secure in production)
jwt.secret=your_super_secret_key_which_is_very_long_123456
jwt.expiration=86400000