spring.application.name=Carepoint

# Server Configuration
server.port=8081

# MongoDB Connection Configuration
spring.data.mongodb.database=hospital_management_db
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017

# Logging Configurations for Mongo Queries
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO

# JSON Formatting for API Responses
spring.jackson.serialization.indent-output=true