spring.application.name=Carepoint

spring.data.mongodb.uri=mongodb://localhost:27017/hms
server.port=8080

logging.level.org.springframework.web=TRACE

# Mail Server Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ranegirish00@gmail.com
spring.mail.password=Girish@224

# SMTP Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

logging.level.org.springframework.security=DEBUG
logging.level.com.hospital=DEBUG